services:
  - type: web
    name: codeigniter-app
    env: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install
    startCommand: "php spark serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_HOST
        value: dpg-csrscdt2ng1s73ad47o0-a
      - key: DB_USERNAME
        value: cultural_heritage_db
      - key: DB_PASSWORD
        value: mJODIfEy8Aph5aEvHpJbmxosWQ9oPFsE
      - key: DB_NAME
        value: cultural_heritage_db
      - key: DB_DRIVER
        value: PostgreSQL
      - key: DB_PORT
        value: "5432"
